package:
  name: shutilspy-visualizer
  version: 0.1.1

source:
  path: ..

build:
  noarch: python
  script: "$PYTHON -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - flask

about:
  summary: 'Python utilities including DAG task framework'
  readme: README.md

  license: MIT
  license_file: LICENSE
  license_family: MIT

  home: https://github.com/shlllshlll/shutilspy 
  dev_url: https://github.com/shlllshlll/shutilspy
  doc_url: https://shlllshlll.github.io/shutilspy/

extra:
  recipe-maintainers:
    - shlllshlll
